packages:
  - packages/*
  - examples/*
  - tools/*
allowBuilds:
  esbuild: true
  lefthook: true
minimumReleaseAgeExclude:
  - rolldown-plugin-dts@0.28.0
  - oxfmt@0.62.0
  - oxlint@1.77.0
  - oxlint-tsgolint@7.0.2001
  - dompurify@3.4.13
  - "@oxfmt/*"
  - "@oxlint/*"
