export const serverDiscoveryFixtures = {
  mastodon: {
    origin: "https://mastodon.example",
    nodeInfo: {
      software: { name: "mastodon", version: "4.3.0" },
      protocols: ["activitypub"],
    },
    oauthMetadata: {
      authorizationEndpoint: "https://mastodon.example/oauth/authorize",
      tokenEndpoint: "https://mastodon.example/oauth/token",
      grantTypesSupported: ["authorization_code"],
    },
    instance: {
      version: "4.3.0",
      urls: { streamingApi: "wss://mastodon.example/api/v1/streaming" },
    },
  },
  misskey: {
    origin: "https://misskey.example",
    nodeInfo: {
      software: { name: "misskey", version: "2025.10.0" },
      protocols: ["activitypub"],
    },
    oauthMetadata: {
      authorizationEndpoint: "https://misskey.example/oauth/authorize",
      tokenEndpoint: "https://misskey.example/oauth/token",
      grantTypesSupported: ["authorization_code"],
    },
    instance: {
      version: "2025.10.0",
    },
    probes: [{ name: "emoji-reactions", supported: true }],
  },
  pleroma: {
    origin: "https://pleroma.example",
    nodeInfo: {
      software: { name: "pleroma", version: "2.7.0" },
      protocols: ["activitypub"],
    },
    probes: [
      { name: "quote-posts", supported: true },
      { name: "emoji-reactions", supported: true },
    ],
  },
  hollo: {
    origin: "https://hollo.example",
    nodeInfo: {
      software: { name: "hollo", version: "0.6.0" },
      protocols: ["activitypub"],
    },
    oauthMetadata: {
      authorizationEndpoint: "https://hollo.example/oauth/authorize",
      tokenEndpoint: "https://hollo.example/oauth/token",
    },
    probes: [{ name: "streaming", supported: false, reason: "Hollo does not expose streaming." }],
  },
  hackerspub: {
    origin: "https://hackers.pub",
    nodeInfo: {
      software: { name: "hackerspub", version: "0.1.0" },
      protocols: ["activitypub"],
    },
    probes: [{ name: "oauth", supported: false, reason: "HackersPub does not use OAuth." }],
  },
} as const;

export const accountMappingFixtures = {
  mastodon: {
    account: {
      id: "109",
      username: "alice",
      acct: "alice",
      display_name: "Alice",
      url: "https://mastodon.example/@alice",
      avatar: "https://mastodon.example/avatar.png",
      header: "https://mastodon.example/header.png",
      bot: false,
      locked: false,
      created_at: "2024-01-01T00:00:00.000Z",
      note: "<p>Hello.</p>",
      followers_count: 10,
      following_count: 20,
      statuses_count: 30,
      fields: [{ name: "Website", value: "https://example.com", verified_at: null }],
    },
    post: {
      id: "900",
      uri: "https://mastodon.example/users/alice/statuses/900",
      url: "https://mastodon.example/@alice/900",
      account: {
        id: "109",
        username: "alice",
        acct: "alice",
        display_name: "Alice",
        url: "https://mastodon.example/@alice",
        avatar: "https://mastodon.example/avatar.png",
        header: "https://mastodon.example/header.png",
        bot: false,
        locked: false,
      },
      content: "<p>Post.</p>",
      created_at: "2024-01-02T00:00:00.000Z",
      visibility: "public",
      sensitive: false,
      spoiler_text: "",
      media_attachments: [],
      replies_count: 1,
      reblogs_count: 2,
      favourites_count: 3,
    },
  },
  misskey: {
    account: {
      id: "9x",
      username: "alice",
      host: null,
      name: "Alice",
      url: "https://misskey.example/@alice",
      avatarUrl: "https://misskey.example/avatar.png",
      bannerUrl: "https://misskey.example/banner.png",
      isBot: false,
      isLocked: false,
      createdAt: "2024-01-01T00:00:00.000Z",
      description: "Hello.",
      followersCount: 10,
      followingCount: 20,
      notesCount: 30,
    },
    post: {
      id: "note9",
      uri: "https://misskey.example/notes/note9",
      url: "https://misskey.example/notes/note9",
      user: {
        id: "9x",
        username: "alice",
        host: null,
        name: "Alice",
        avatarUrl: "https://misskey.example/avatar.png",
        isBot: false,
        isLocked: false,
      },
      text: "Post.",
      cw: null,
      createdAt: "2024-01-02T00:00:00.000Z",
      visibility: "public",
      files: [],
      repliesCount: 1,
      renoteCount: 2,
      reactions: { "⭐": 3 },
    },
  },
  pleroma: {
    inherits: "mastodon",
  },
  hollo: {
    inherits: "mastodon",
  },
  hackerspub: {
    account: {
      id: "actor-1",
      uuid: "actor-1",
      iri: "https://hackers.pub/@alice",
      username: "alice",
      handle: "alice@hackers.pub",
      rawName: "Alice",
      bio: "<p>Hello.</p>",
      avatarUrl: "https://hackers.pub/avatar.png",
      automaticallyApprovesFollowers: true,
      url: "https://hackers.pub/@alice",
      created: "2024-01-01T00:00:00.000Z",
      fields: [{ name: "Website", value: "https://example.com" }],
    },
    post: {
      id: "post-1",
      uuid: "post-1",
      iri: "https://hackers.pub/posts/post-1",
      url: "https://hackers.pub/posts/post-1",
      html: "<p>Post.</p>",
      created: "2024-01-02T00:00:00.000Z",
      visibility: "PUBLIC",
      actor: {
        id: "actor-1",
        uuid: "actor-1",
        iri: "https://hackers.pub/@alice",
        username: "alice",
        handle: "alice@hackers.pub",
        rawName: "Alice",
        avatarUrl: "https://hackers.pub/avatar.png",
        created: "2024-01-01T00:00:00.000Z",
      },
    },
  },
} as const;
