export const publicOperationMatrix = [
  {
    graphqlType: "query",
    graphqlField: "capabilities",
    graphqlArgs: ["adapter", "origin"],
    graphqlReturnType: "CapabilitySet",
    httpMethod: "get",
    httpPath: "/api/v1/instances/{origin}/capabilities",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/CapabilitySet",
  },
  {
    graphqlType: "query",
    graphqlField: "instance",
    graphqlArgs: ["adapter", "origin"],
    graphqlReturnType: "Instance",
    httpMethod: "get",
    httpPath: "/api/v1/instances/{origin}",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/InstanceProfile",
  },
  {
    graphqlType: "query",
    graphqlField: "detectInstance",
    graphqlArgs: ["input"],
    graphqlReturnType: "Instance",
    httpMethod: "post",
    httpPath: "/api/v1/instances/detect",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/InstanceProfile",
  },
  {
    graphqlType: "query",
    graphqlField: "account",
    graphqlArgs: ["id"],
    graphqlReturnType: "Account",
    httpMethod: "get",
    httpPath: "/api/v1/accounts/{id}",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/Account",
  },
  {
    graphqlType: "query",
    graphqlField: "accountByHandle",
    graphqlArgs: ["adapter", "handle", "origin"],
    graphqlReturnType: "Account",
    httpMethod: "get",
    httpPath: "/api/v1/accounts/lookup",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/Account",
  },
  {
    graphqlType: "query",
    graphqlField: "accountPosts",
    graphqlArgs: ["id", "page", "sessionId"],
    graphqlReturnType: "PostConnection",
    httpMethod: "get",
    httpPath: "/api/v1/accounts/{id}/posts",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/Post",
  },
  {
    graphqlType: "query",
    graphqlField: "accountRelationship",
    graphqlArgs: ["id", "sessionId"],
    graphqlReturnType: "Relationship",
    httpMethod: "get",
    httpPath: "/api/v1/accounts/{id}/relationships",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/Relationship",
  },
  {
    graphqlType: "mutation",
    graphqlField: "importToken",
    graphqlArgs: ["input"],
    graphqlReturnType: "AuthSession",
    httpMethod: "post",
    httpPath: "/api/v1/auth/import-token",
    httpRequestRef: "#/components/schemas/AuthImportTokenRequest",
    httpResponseDataRef: "#/components/schemas/AuthSession",
  },
  {
    graphqlType: "mutation",
    graphqlField: "authStart",
    graphqlArgs: ["input"],
    graphqlReturnType: "AuthStartPayload",
    httpMethod: "post",
    httpPath: "/api/v1/auth/start",
    httpRequestRef: "#/components/schemas/AuthStartRequest",
    httpResponseDataRef: "#/components/schemas/AuthStartPayload",
  },
  {
    graphqlType: "mutation",
    graphqlField: "authParseCallback",
    graphqlArgs: ["input"],
    graphqlReturnType: "ParsedAuthCallback",
    httpMethod: "post",
    httpPath: "/api/v1/auth/parse-callback",
    httpRequestRef: "#/components/schemas/AuthCallbackInput",
    httpResponseDataRef: "#/components/schemas/ParsedAuthCallback",
  },
  {
    graphqlType: "mutation",
    graphqlField: "authExchange",
    graphqlArgs: ["input"],
    graphqlReturnType: "AuthSession",
    httpMethod: "post",
    httpPath: "/api/v1/auth/exchange",
    httpRequestRef: "#/components/schemas/AuthExchangeRequest",
    httpResponseDataRef: "#/components/schemas/AuthSession",
  },
  {
    graphqlType: "mutation",
    graphqlField: "authRefresh",
    graphqlArgs: ["sessionId"],
    graphqlReturnType: "AuthSession",
    httpMethod: "post",
    httpPath: "/api/v1/auth/refresh",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/AuthSession",
  },
  {
    graphqlType: "mutation",
    graphqlField: "authRevoke",
    graphqlArgs: ["sessionId"],
    graphqlReturnType: "Boolean",
    httpMethod: "post",
    httpPath: "/api/v1/auth/revoke",
    httpRequestRef: undefined,
    httpResponseDataRef: undefined,
  },
  {
    graphqlType: "mutation",
    graphqlField: "uploadMedia",
    graphqlArgs: ["input"],
    graphqlReturnType: "MediaAttachment",
    httpMethod: "post",
    httpPath: "/api/v1/media",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/MediaAttachment",
  },
  {
    graphqlType: "query",
    graphqlField: "viewer",
    graphqlArgs: ["sessionId"],
    graphqlReturnType: "Account",
    httpMethod: "get",
    httpPath: "/api/v1/viewer",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/Account",
  },
  {
    graphqlType: "query",
    graphqlField: "post",
    graphqlArgs: ["id"],
    graphqlReturnType: "Post",
    httpMethod: "get",
    httpPath: "/api/v1/posts/{id}",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/Post",
  },
  {
    graphqlType: "query",
    graphqlField: "homeTimeline",
    graphqlArgs: ["origin", "page", "sessionId"],
    graphqlReturnType: "TimelineConnection",
    httpMethod: "get",
    httpPath: "/api/v1/timelines/home",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/Post",
  },
  {
    graphqlType: "query",
    graphqlField: "publicTimeline",
    graphqlArgs: ["adapter", "local", "origin", "page", "sessionId"],
    graphqlReturnType: "TimelineConnection",
    httpMethod: "get",
    httpPath: "/api/v1/timelines/public",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/Post",
  },
  {
    graphqlType: "query",
    graphqlField: "hashtagTimeline",
    graphqlArgs: ["adapter", "origin", "page", "tag"],
    graphqlReturnType: "TimelineConnection",
    httpMethod: "get",
    httpPath: "/api/v1/timelines/hashtags/{tag}",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/Post",
  },
  {
    graphqlType: "query",
    graphqlField: "search",
    graphqlArgs: ["input"],
    graphqlReturnType: "SearchResult",
    httpMethod: "get",
    httpPath: "/api/v1/search",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/SearchResult",
  },
  {
    graphqlType: "mutation",
    graphqlField: "createPost",
    graphqlArgs: ["input"],
    graphqlReturnType: "Post",
    httpMethod: "post",
    httpPath: "/api/v1/posts",
    httpRequestRef: "#/components/schemas/CreatePostRequest",
    httpResponseDataRef: "#/components/schemas/Post",
  },
  {
    graphqlType: "mutation",
    graphqlField: "deletePost",
    graphqlArgs: ["id", "sessionId"],
    graphqlReturnType: "DeletedEntity",
    httpMethod: "delete",
    httpPath: "/api/v1/posts/{id}",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/DeletedEntity",
  },
  {
    graphqlType: "mutation",
    graphqlField: "followAccount",
    graphqlArgs: ["id", "sessionId"],
    graphqlReturnType: "Relationship",
    httpMethod: "post",
    httpPath: "/api/v1/accounts/{id}/follow",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/Relationship",
  },
  {
    graphqlType: "mutation",
    graphqlField: "unfollowAccount",
    graphqlArgs: ["id", "sessionId"],
    graphqlReturnType: "Relationship",
    httpMethod: "post",
    httpPath: "/api/v1/accounts/{id}/unfollow",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/Relationship",
  },
  {
    graphqlType: "mutation",
    graphqlField: "blockAccount",
    graphqlArgs: ["id", "sessionId"],
    graphqlReturnType: "Relationship",
    httpMethod: "post",
    httpPath: "/api/v1/accounts/{id}/block",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/Relationship",
  },
  {
    graphqlType: "mutation",
    graphqlField: "unblockAccount",
    graphqlArgs: ["id", "sessionId"],
    graphqlReturnType: "Relationship",
    httpMethod: "post",
    httpPath: "/api/v1/accounts/{id}/unblock",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/Relationship",
  },
  {
    graphqlType: "mutation",
    graphqlField: "muteAccount",
    graphqlArgs: ["input"],
    graphqlReturnType: "Relationship",
    httpMethod: "post",
    httpPath: "/api/v1/accounts/{id}/mute",
    httpRequestRef: "#/components/schemas/MuteAccountRequest",
    httpResponseDataRef: "#/components/schemas/Relationship",
  },
  {
    graphqlType: "mutation",
    graphqlField: "unmuteAccount",
    graphqlArgs: ["id", "sessionId"],
    graphqlReturnType: "Relationship",
    httpMethod: "post",
    httpPath: "/api/v1/accounts/{id}/unmute",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/Relationship",
  },
  {
    graphqlType: "mutation",
    graphqlField: "favouritePost",
    graphqlArgs: ["id", "sessionId"],
    graphqlReturnType: "Post",
    httpMethod: "post",
    httpPath: "/api/v1/posts/{id}/favourite",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/Post",
  },
  {
    graphqlType: "mutation",
    graphqlField: "unfavouritePost",
    graphqlArgs: ["id", "sessionId"],
    graphqlReturnType: "Post",
    httpMethod: "post",
    httpPath: "/api/v1/posts/{id}/unfavourite",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/Post",
  },
  {
    graphqlType: "mutation",
    graphqlField: "bookmarkPost",
    graphqlArgs: ["id", "sessionId"],
    graphqlReturnType: "Post",
    httpMethod: "post",
    httpPath: "/api/v1/posts/{id}/bookmark",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/Post",
  },
  {
    graphqlType: "mutation",
    graphqlField: "unbookmarkPost",
    graphqlArgs: ["id", "sessionId"],
    graphqlReturnType: "Post",
    httpMethod: "post",
    httpPath: "/api/v1/posts/{id}/unbookmark",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/Post",
  },
  {
    graphqlType: "mutation",
    graphqlField: "boostPost",
    graphqlArgs: ["input"],
    graphqlReturnType: "Post",
    httpMethod: "post",
    httpPath: "/api/v1/posts/{id}/boost",
    httpRequestRef: "#/components/schemas/BoostPostRequest",
    httpResponseDataRef: "#/components/schemas/Post",
  },
  {
    graphqlType: "mutation",
    graphqlField: "unboostPost",
    graphqlArgs: ["id", "sessionId"],
    graphqlReturnType: "Post",
    httpMethod: "post",
    httpPath: "/api/v1/posts/{id}/unboost",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/Post",
  },
  {
    graphqlType: "mutation",
    graphqlField: "reactToPost",
    graphqlArgs: ["input"],
    graphqlReturnType: "Post",
    httpMethod: "post",
    httpPath: "/api/v1/posts/{id}/reactions",
    httpRequestRef: "#/components/schemas/ReactPostRequest",
    httpResponseDataRef: "#/components/schemas/Post",
  },
  {
    graphqlType: "mutation",
    graphqlField: "unreactToPost",
    graphqlArgs: ["input"],
    graphqlReturnType: "Post",
    httpMethod: "delete",
    httpPath: "/api/v1/posts/{id}/reactions/{emoji}",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/Post",
  },
  {
    graphqlType: "query",
    graphqlField: "poll",
    graphqlArgs: ["id", "sessionId"],
    graphqlReturnType: "Poll",
    httpMethod: "get",
    httpPath: "/api/v1/polls/{id}",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/Poll",
  },
  {
    graphqlType: "mutation",
    graphqlField: "votePoll",
    graphqlArgs: ["input"],
    graphqlReturnType: "Poll",
    httpMethod: "post",
    httpPath: "/api/v1/polls/{id}/votes",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/Poll",
  },
] as const;

export const reservedOperationMatrix = [
  reserved("query", "postContext", "PostContext", "get", "/api/v1/posts/{id}/context", false),
  reserved("query", "postQuotes", "PostConnection", "get", "/api/v1/posts/{id}/quotes", false),
  reserved(
    "query",
    "listTimeline",
    "TimelineConnection",
    "get",
    "/api/v1/timelines/lists/{id}",
    true,
  ),
  reserved(
    "query",
    "notifications",
    "NotificationConnection",
    "get",
    "/api/v1/notifications",
    true,
  ),
  reserved(
    "query",
    "notificationUnreadCount",
    "Int",
    "get",
    "/api/v1/notifications/unread-count",
    true,
  ),
  reserved("query", "followRequests", "AccountConnection", "get", "/api/v1/follow-requests", true),
  reserved("query", "lists", "ListConnection", "get", "/api/v1/lists", true),
  reserved("query", "list", "List", "get", "/api/v1/lists/{id}", true),
  reserved(
    "query",
    "listAccounts",
    "AccountConnection",
    "get",
    "/api/v1/lists/{id}/accounts",
    true,
  ),
  reserved(
    "mutation",
    "ingestMediaFromUrl",
    "MediaAttachment",
    "post",
    "/api/v1/media/ingest-url",
    true,
  ),
  reserved("mutation", "updatePost", "Post", "patch", "/api/v1/posts/{id}", true),
  reserved(
    "mutation",
    "acceptFollowRequest",
    "Relationship",
    "post",
    "/api/v1/follow-requests/{id}/accept",
    true,
  ),
  reserved(
    "mutation",
    "rejectFollowRequest",
    "Relationship",
    "post",
    "/api/v1/follow-requests/{id}/reject",
    true,
  ),
  reserved("mutation", "createList", "List", "post", "/api/v1/lists", true),
  reserved("mutation", "updateList", "List", "patch", "/api/v1/lists/{id}", true),
  reserved("mutation", "deleteList", "List", "delete", "/api/v1/lists/{id}", true),
  reserved("mutation", "addListAccount", "List", "post", "/api/v1/lists/{id}/accounts", true),
  reserved("mutation", "removeListAccount", "List", "delete", "/api/v1/lists/{id}/accounts", true),
  reserved(
    "mutation",
    "dismissNotification",
    "Boolean",
    "post",
    "/api/v1/notifications/{id}/dismiss",
    true,
  ),
  reserved(
    "mutation",
    "clearNotifications",
    "Boolean",
    "post",
    "/api/v1/notifications/clear",
    true,
  ),
] as const;

export const implementedHttpOnlyOperations = new Set([
  "GET /api/v1/timelines/local",
  "POST /api/v1/media",
]);

export const reservedHttpOnlyOperations = new Set([
  "GET /api/v1/media/{id}",
  "PATCH /api/v1/media/{id}",
  "DELETE /api/v1/media/{id}",
  "GET /api/v1/streams",
  "GET /api/v1/streams/timelines/home",
  "GET /api/v1/streams/notifications",
]);

export const authenticatedHttpOnlyOperations = new Set([
  "POST /api/v1/media",
  "PATCH /api/v1/media/{id}",
  "DELETE /api/v1/media/{id}",
  "GET /api/v1/streams",
  "GET /api/v1/streams/timelines/home",
  "GET /api/v1/streams/notifications",
]);

export const standaloneHttpOperations = new Set([
  "GET /health",
  "GET /api/v1",
  "GET /api/v1/openapi.json",
]);

export const standaloneGraphQLOperations = new Set(["query apiVersion", "query health"]);

export const reservedGraphQLOperations = new Set(
  reservedOperationMatrix.map((operation) => `${operation.graphqlType} ${operation.graphqlField}`),
);

function reserved(
  graphqlType: "query" | "mutation",
  graphqlField: string,
  graphqlReturnType: string,
  httpMethod: "get" | "post" | "patch" | "delete",
  httpPath: string,
  requiresAuth: boolean,
) {
  return {
    graphqlType,
    graphqlField,
    graphqlReturnType,
    httpMethod,
    httpPath,
    requiresAuth,
  };
}
