import { publicOperations, type PublicOperationName } from "@activityplug/core";

export const lifecycleStatusOperations = new Set<PublicOperationName>(["auth.verifyCredentials"]);

export const streamingOperations = new Set<PublicOperationName>([
  "stream.timeline",
  "stream.notifications",
  "stream.conversations",
]);

export const publicTransportOperations = publicOperations
  .map(({ name }) => name)
  .filter((name) => !lifecycleStatusOperations.has(name) && !streamingOperations.has(name));

export const publicOperationMatrix = [
  {
    operation: publicOperationName("capabilities"),
    graphqlType: "query",
    graphqlField: "capabilities",
    graphqlArgs: ["adapter", "origin"],
    graphqlReturnType: "CapabilitySet",
    httpMethod: "get",
    httpPath: "/api/v1/instances/{origin}/capabilities",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/CapabilitySet",
  },
  {
    operation: publicOperationName("instance.get"),
    graphqlType: "query",
    graphqlField: "instance",
    graphqlArgs: ["adapter", "origin"],
    graphqlReturnType: "Instance",
    httpMethod: "get",
    httpPath: "/api/v1/instances/{origin}",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/InstanceProfile",
  },
  {
    operation: publicOperationName("instance.detect"),
    graphqlType: "query",
    graphqlField: "detectInstance",
    graphqlArgs: ["input"],
    graphqlReturnType: "Instance",
    httpMethod: "post",
    httpPath: "/api/v1/instances/detect",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/InstanceProfile",
  },
  {
    operation: publicOperationName("account.get"),
    graphqlType: "query",
    graphqlField: "account",
    graphqlArgs: ["id"],
    graphqlReturnType: "Account",
    httpMethod: "get",
    httpPath: "/api/v1/accounts/{id}",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/Account",
  },
  {
    operation: publicOperationName("account.lookup"),
    graphqlType: "query",
    graphqlField: "accountByHandle",
    graphqlArgs: ["adapter", "handle", "origin"],
    graphqlReturnType: "Account",
    httpMethod: "get",
    httpPath: "/api/v1/accounts/lookup",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/Account",
  },
  {
    operation: publicOperationName("account.posts"),
    graphqlType: "query",
    graphqlField: "accountPosts",
    graphqlArgs: ["id", "page"],
    graphqlReturnType: "PostConnection",
    httpMethod: "get",
    httpPath: "/api/v1/accounts/{id}/posts",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/Post",
  },
  {
    operation: publicOperationName("account.followers"),
    graphqlType: "query",
    graphqlField: "accountFollowers",
    graphqlArgs: ["id", "page"],
    graphqlReturnType: "AccountConnection",
    httpMethod: "get",
    httpPath: "/api/v1/accounts/{id}/followers",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/Account",
  },
  {
    operation: publicOperationName("account.following"),
    graphqlType: "query",
    graphqlField: "accountFollowing",
    graphqlArgs: ["id", "page"],
    graphqlReturnType: "AccountConnection",
    httpMethod: "get",
    httpPath: "/api/v1/accounts/{id}/following",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/Account",
  },
  {
    operation: publicOperationName("account.relationships"),
    graphqlType: "query",
    graphqlField: "accountRelationship",
    graphqlArgs: ["id"],
    graphqlReturnType: "Relationship",
    httpMethod: "get",
    httpPath: "/api/v1/accounts/{id}/relationships",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/Relationship",
  },
  {
    operation: publicOperationName("auth.tokenInjection"),
    graphqlType: "mutation",
    graphqlField: "importToken",
    graphqlArgs: ["input"],
    graphqlReturnType: "AuthSession",
    httpMethod: "post",
    httpPath: "/api/v1/auth/import-token",
    httpRequestRef: "#/components/schemas/AuthImportTokenRequest",
    httpResponseDataRef: "#/components/schemas/AuthSession",
  },
  {
    operation: publicOperationName("auth.oauth.authorizationUrl"),
    graphqlType: "mutation",
    graphqlField: "authStart",
    graphqlArgs: ["input"],
    graphqlReturnType: "AuthStartPayload",
    httpMethod: "post",
    httpPath: "/api/v1/auth/start",
    httpRequestRef: "#/components/schemas/AuthStartRequest",
    httpResponseDataRef: "#/components/schemas/AuthStartPayload",
  },
  {
    operation: publicOperationName("auth.oauth.callback"),
    graphqlType: "mutation",
    graphqlField: "authParseCallback",
    graphqlArgs: ["input"],
    graphqlReturnType: "ParsedAuthCallback",
    httpMethod: "post",
    httpPath: "/api/v1/auth/parse-callback",
    httpRequestRef: "#/components/schemas/AuthCallbackInput",
    httpResponseDataRef: "#/components/schemas/ParsedAuthCallback",
  },
  {
    operation: publicOperationName("auth.oauth.exchangeCode"),
    graphqlType: "mutation",
    graphqlField: "authExchange",
    graphqlArgs: ["input"],
    graphqlReturnType: "AuthSession",
    httpMethod: "post",
    httpPath: "/api/v1/auth/exchange",
    httpRequestRef: "#/components/schemas/AuthExchangeRequest",
    httpResponseDataRef: "#/components/schemas/AuthSession",
  },
  {
    operation: publicOperationName("auth.oauth.refresh"),
    graphqlType: "mutation",
    graphqlField: "authRefresh",
    graphqlArgs: [],
    graphqlReturnType: "AuthSession",
    httpMethod: "post",
    httpPath: "/api/v1/auth/refresh",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/AuthSession",
  },
  {
    operation: publicOperationName("auth.oauth.revoke"),
    graphqlType: "mutation",
    graphqlField: "authRevoke",
    graphqlArgs: [],
    graphqlReturnType: "Boolean",
    httpMethod: "post",
    httpPath: "/api/v1/auth/revoke",
    httpRequestRef: undefined,
    httpResponseDataRef: undefined,
  },
  {
    operation: publicOperationName("auth.emailChallenge.start"),
    graphqlType: "mutation",
    graphqlField: "authEmailChallengeStart",
    graphqlArgs: ["input"],
    graphqlReturnType: "EmailChallengeStartPayload",
    httpMethod: "post",
    httpPath: "/api/v1/auth/email-challenge/start",
    httpRequestRef: "#/components/schemas/EmailChallengeStartRequest",
    httpResponseDataRef: "#/components/schemas/EmailChallengeStartPayload",
  },
  {
    operation: publicOperationName("auth.emailChallenge.verify"),
    graphqlType: "mutation",
    graphqlField: "authEmailChallengeVerify",
    graphqlArgs: ["input"],
    graphqlReturnType: "AuthSession",
    httpMethod: "post",
    httpPath: "/api/v1/auth/email-challenge/verify",
    httpRequestRef: "#/components/schemas/EmailChallengeVerifyRequest",
    httpResponseDataRef: "#/components/schemas/AuthSession",
  },
  {
    operation: publicOperationName("auth.passkey.start"),
    graphqlType: "mutation",
    graphqlField: "authPasskeyStart",
    graphqlArgs: ["input"],
    graphqlReturnType: "PasskeyStartPayload",
    httpMethod: "post",
    httpPath: "/api/v1/auth/passkey/start",
    httpRequestRef: "#/components/schemas/PasskeyStartRequest",
    httpResponseDataRef: "#/components/schemas/PasskeyStartPayload",
  },
  {
    operation: publicOperationName("auth.passkey.finish"),
    graphqlType: "mutation",
    graphqlField: "authPasskeyFinish",
    graphqlArgs: ["input"],
    graphqlReturnType: "AuthSession",
    httpMethod: "post",
    httpPath: "/api/v1/auth/passkey/finish",
    httpRequestRef: "#/components/schemas/PasskeyFinishRequest",
    httpResponseDataRef: "#/components/schemas/AuthSession",
  },
  {
    operation: publicOperationName("media.upload"),
    graphqlType: "mutation",
    graphqlField: "uploadMedia",
    graphqlArgs: ["input"],
    graphqlReturnType: "MediaAttachment",
    httpMethod: "post",
    httpPath: "/api/v1/media",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/MediaAttachment",
  },
  {
    operation: publicOperationName("media.ingestUrl"),
    graphqlType: "mutation",
    graphqlField: "ingestMediaFromUrl",
    graphqlArgs: ["input"],
    graphqlReturnType: "MediaAttachment",
    httpMethod: "post",
    httpPath: "/api/v1/media/ingest-url",
    httpRequestRef: "#/components/schemas/UploadMediaFromUrlRequest",
    httpResponseDataRef: "#/components/schemas/MediaAttachment",
  },
  {
    operation: publicOperationName("media.update"),
    graphqlType: "mutation",
    graphqlField: "updateMedia",
    graphqlArgs: ["input"],
    graphqlReturnType: "MediaAttachment",
    httpMethod: "patch",
    httpPath: "/api/v1/media/{id}",
    httpRequestRef: "#/components/schemas/UpdateMediaRequest",
    httpResponseDataRef: "#/components/schemas/MediaAttachment",
  },
  {
    operation: publicOperationName("media.delete"),
    graphqlType: "mutation",
    graphqlField: "deleteMedia",
    graphqlArgs: ["input"],
    graphqlReturnType: "DeletedEntity",
    httpMethod: "delete",
    httpPath: "/api/v1/media/{id}",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/DeletedEntity",
  },
  {
    operation: publicOperationName("account.updateProfile"),
    graphqlType: "mutation",
    graphqlField: "updateProfile",
    graphqlArgs: ["input"],
    graphqlReturnType: "Account",
    httpMethod: "patch",
    httpPath: "/api/v1/accounts/update-profile",
    httpRequestRef: "#/components/schemas/UpdateProfileRequest",
    httpResponseDataRef: "#/components/schemas/Account",
  },
  {
    operation: publicOperationName("viewer"),
    graphqlType: "query",
    graphqlField: "viewer",
    graphqlArgs: [],
    graphqlReturnType: "Account",
    httpMethod: "get",
    httpPath: "/api/v1/viewer",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/Account",
  },
  {
    operation: publicOperationName("post.get"),
    graphqlType: "query",
    graphqlField: "post",
    graphqlArgs: ["id"],
    graphqlReturnType: "Post",
    httpMethod: "get",
    httpPath: "/api/v1/posts/{id}",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/Post",
  },
  {
    operation: publicOperationName("timeline.home"),
    graphqlType: "query",
    graphqlField: "homeTimeline",
    graphqlArgs: ["origin", "page"],
    graphqlReturnType: "TimelineConnection",
    httpMethod: "get",
    httpPath: "/api/v1/timelines/home",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/Post",
  },
  {
    operation: publicOperationName("timeline.public"),
    graphqlType: "query",
    graphqlField: "publicTimeline",
    graphqlArgs: ["adapter", "local", "origin", "page"],
    graphqlReturnType: "TimelineConnection",
    httpMethod: "get",
    httpPath: "/api/v1/timelines/public",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/Post",
  },
  {
    operation: publicOperationName("timeline.hashtag"),
    graphqlType: "query",
    graphqlField: "hashtagTimeline",
    graphqlArgs: ["adapter", "origin", "page", "tag"],
    graphqlReturnType: "TimelineConnection",
    httpMethod: "get",
    httpPath: "/api/v1/timelines/hashtags/{tag}",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/Post",
  },
  {
    operation: publicOperationName("search"),
    graphqlType: "query",
    graphqlField: "search",
    graphqlArgs: ["input"],
    graphqlReturnType: "SearchResult",
    httpMethod: "get",
    httpPath: "/api/v1/search",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/SearchResult",
  },
  {
    operation: publicOperationName("post.create"),
    graphqlType: "mutation",
    graphqlField: "createPost",
    graphqlArgs: ["input"],
    graphqlReturnType: "Post",
    httpMethod: "post",
    httpPath: "/api/v1/posts",
    httpRequestRef: "#/components/schemas/CreatePostRequest",
    httpResponseDataRef: "#/components/schemas/Post",
  },
  {
    operation: publicOperationName("post.delete"),
    graphqlType: "mutation",
    graphqlField: "deletePost",
    graphqlArgs: ["id"],
    graphqlReturnType: "DeletedEntity",
    httpMethod: "delete",
    httpPath: "/api/v1/posts/{id}",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/DeletedEntity",
  },
  {
    operation: publicOperationName("post.update"),
    graphqlType: "mutation",
    graphqlField: "updatePost",
    graphqlArgs: ["input"],
    graphqlReturnType: "Post",
    httpMethod: "patch",
    httpPath: "/api/v1/posts/{id}",
    httpRequestRef: "#/components/schemas/UpdatePostRequest",
    httpResponseDataRef: "#/components/schemas/Post",
  },
  {
    operation: publicOperationName("social.follow"),
    graphqlType: "mutation",
    graphqlField: "followAccount",
    graphqlArgs: ["id"],
    graphqlReturnType: "Relationship",
    httpMethod: "post",
    httpPath: "/api/v1/accounts/{id}/follow",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/Relationship",
  },
  {
    operation: publicOperationName("social.unfollow"),
    graphqlType: "mutation",
    graphqlField: "unfollowAccount",
    graphqlArgs: ["id"],
    graphqlReturnType: "Relationship",
    httpMethod: "post",
    httpPath: "/api/v1/accounts/{id}/unfollow",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/Relationship",
  },
  {
    operation: publicOperationName("social.block"),
    graphqlType: "mutation",
    graphqlField: "blockAccount",
    graphqlArgs: ["id"],
    graphqlReturnType: "Relationship",
    httpMethod: "post",
    httpPath: "/api/v1/accounts/{id}/block",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/Relationship",
  },
  {
    operation: publicOperationName("social.unblock"),
    graphqlType: "mutation",
    graphqlField: "unblockAccount",
    graphqlArgs: ["id"],
    graphqlReturnType: "Relationship",
    httpMethod: "post",
    httpPath: "/api/v1/accounts/{id}/unblock",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/Relationship",
  },
  {
    operation: publicOperationName("social.mute"),
    graphqlType: "mutation",
    graphqlField: "muteAccount",
    graphqlArgs: ["input"],
    graphqlReturnType: "Relationship",
    httpMethod: "post",
    httpPath: "/api/v1/accounts/{id}/mute",
    httpRequestRef: "#/components/schemas/MuteAccountRequest",
    httpResponseDataRef: "#/components/schemas/Relationship",
  },
  {
    operation: publicOperationName("social.unmute"),
    graphqlType: "mutation",
    graphqlField: "unmuteAccount",
    graphqlArgs: ["id"],
    graphqlReturnType: "Relationship",
    httpMethod: "post",
    httpPath: "/api/v1/accounts/{id}/unmute",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/Relationship",
  },
  {
    operation: publicOperationName("social.favourite"),
    graphqlType: "mutation",
    graphqlField: "favouritePost",
    graphqlArgs: ["id"],
    graphqlReturnType: "Post",
    httpMethod: "post",
    httpPath: "/api/v1/posts/{id}/favourite",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/Post",
  },
  {
    operation: publicOperationName("social.unfavourite"),
    graphqlType: "mutation",
    graphqlField: "unfavouritePost",
    graphqlArgs: ["id"],
    graphqlReturnType: "Post",
    httpMethod: "post",
    httpPath: "/api/v1/posts/{id}/unfavourite",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/Post",
  },
  {
    operation: publicOperationName("social.bookmark"),
    graphqlType: "mutation",
    graphqlField: "bookmarkPost",
    graphqlArgs: ["id"],
    graphqlReturnType: "Post",
    httpMethod: "post",
    httpPath: "/api/v1/posts/{id}/bookmark",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/Post",
  },
  {
    operation: publicOperationName("social.unbookmark"),
    graphqlType: "mutation",
    graphqlField: "unbookmarkPost",
    graphqlArgs: ["id"],
    graphqlReturnType: "Post",
    httpMethod: "post",
    httpPath: "/api/v1/posts/{id}/unbookmark",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/Post",
  },
  {
    operation: publicOperationName("social.boost"),
    graphqlType: "mutation",
    graphqlField: "boostPost",
    graphqlArgs: ["input"],
    graphqlReturnType: "Post",
    httpMethod: "post",
    httpPath: "/api/v1/posts/{id}/boost",
    httpRequestRef: "#/components/schemas/BoostPostRequest",
    httpResponseDataRef: "#/components/schemas/Post",
  },
  {
    operation: publicOperationName("social.unboost"),
    graphqlType: "mutation",
    graphqlField: "unboostPost",
    graphqlArgs: ["id"],
    graphqlReturnType: "Post",
    httpMethod: "post",
    httpPath: "/api/v1/posts/{id}/unboost",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/Post",
  },
  {
    operation: publicOperationName("social.reaction"),
    graphqlType: "mutation",
    graphqlField: "reactToPost",
    graphqlArgs: ["input"],
    graphqlReturnType: "Post",
    httpMethod: "post",
    httpPath: "/api/v1/posts/{id}/reactions",
    httpRequestRef: "#/components/schemas/ReactPostRequest",
    httpResponseDataRef: "#/components/schemas/Post",
  },
  {
    operation: publicOperationName("social.unreaction"),
    graphqlType: "mutation",
    graphqlField: "unreactToPost",
    graphqlArgs: ["input"],
    graphqlReturnType: "Post",
    httpMethod: "delete",
    httpPath: "/api/v1/posts/{id}/reactions/{emoji}",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/Post",
  },
  {
    operation: publicOperationName("poll.get"),
    graphqlType: "query",
    graphqlField: "poll",
    graphqlArgs: ["id"],
    graphqlReturnType: "Poll",
    httpMethod: "get",
    httpPath: "/api/v1/polls/{id}",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/Poll",
  },
  {
    operation: publicOperationName("poll.vote"),
    graphqlType: "mutation",
    graphqlField: "votePoll",
    graphqlArgs: ["input"],
    graphqlReturnType: "Poll",
    httpMethod: "post",
    httpPath: "/api/v1/polls/{id}/votes",
    httpRequestRef: undefined,
    httpRequestRequiredFields: ["choices"],
    httpResponseDataRef: "#/components/schemas/Poll",
  },
  {
    operation: publicOperationName("timeline.list"),
    graphqlType: "query",
    graphqlField: "listTimeline",
    graphqlArgs: ["listId", "page"],
    graphqlReturnType: "TimelineConnection",
    httpMethod: "get",
    httpPath: "/api/v1/timelines/lists/{id}",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/Post",
  },
  {
    operation: publicOperationName("notification.list"),
    graphqlType: "query",
    graphqlField: "notifications",
    graphqlArgs: ["adapter", "origin", "page", "types"],
    graphqlReturnType: "NotificationConnection",
    httpMethod: "get",
    httpPath: "/api/v1/notifications",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/Notification",
  },
  {
    operation: publicOperationName("notification.unreadCount"),
    graphqlType: "query",
    graphqlField: "notificationUnreadCount",
    graphqlArgs: ["adapter", "origin"],
    graphqlReturnType: "Int",
    httpMethod: "get",
    httpPath: "/api/v1/notifications/unread-count",
    httpRequestRef: undefined,
    httpResponseInlineFields: ["count"],
    httpResponseDataRef: undefined,
  },
  {
    operation: publicOperationName("followRequest.list"),
    graphqlType: "query",
    graphqlField: "followRequests",
    graphqlArgs: ["adapter", "origin", "page"],
    graphqlReturnType: "AccountConnection",
    httpMethod: "get",
    httpPath: "/api/v1/follow-requests",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/Account",
  },
  {
    operation: publicOperationName("list.list"),
    graphqlType: "query",
    graphqlField: "lists",
    graphqlArgs: ["adapter", "origin", "page"],
    graphqlReturnType: "ListConnection",
    httpMethod: "get",
    httpPath: "/api/v1/lists",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/List",
  },
  {
    operation: publicOperationName("list.get"),
    graphqlType: "query",
    graphqlField: "list",
    graphqlArgs: ["id"],
    graphqlReturnType: "List",
    httpMethod: "get",
    httpPath: "/api/v1/lists/{id}",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/List",
  },
  {
    operation: publicOperationName("list.accounts"),
    graphqlType: "query",
    graphqlField: "listAccounts",
    graphqlArgs: ["id", "page"],
    graphqlReturnType: "AccountConnection",
    httpMethod: "get",
    httpPath: "/api/v1/lists/{id}/accounts",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/Account",
  },
  {
    operation: publicOperationName("followRequest.accept"),
    graphqlType: "mutation",
    graphqlField: "acceptFollowRequest",
    graphqlArgs: ["id"],
    graphqlReturnType: "Relationship",
    httpMethod: "post",
    httpPath: "/api/v1/follow-requests/{id}/accept",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/Relationship",
  },
  {
    operation: publicOperationName("followRequest.reject"),
    graphqlType: "mutation",
    graphqlField: "rejectFollowRequest",
    graphqlArgs: ["id"],
    graphqlReturnType: "Relationship",
    httpMethod: "post",
    httpPath: "/api/v1/follow-requests/{id}/reject",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/Relationship",
  },
  {
    operation: publicOperationName("list.create"),
    graphqlType: "mutation",
    graphqlField: "createList",
    graphqlArgs: ["input"],
    graphqlReturnType: "List",
    httpMethod: "post",
    httpPath: "/api/v1/lists",
    httpRequestRef: undefined,
    httpRequestRequiredFields: ["origin", "title"],
    httpResponseDataRef: "#/components/schemas/List",
  },
  {
    operation: publicOperationName("list.update"),
    graphqlType: "mutation",
    graphqlField: "updateList",
    graphqlArgs: ["input"],
    graphqlReturnType: "List",
    httpMethod: "patch",
    httpPath: "/api/v1/lists/{id}",
    httpRequestRef: undefined,
    httpRequestRequiredFields: ["title"],
    httpResponseDataRef: "#/components/schemas/List",
  },
  {
    operation: publicOperationName("list.delete"),
    graphqlType: "mutation",
    graphqlField: "deleteList",
    graphqlArgs: ["id"],
    graphqlReturnType: "DeletedEntity",
    httpMethod: "delete",
    httpPath: "/api/v1/lists/{id}",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/DeletedEntity",
  },
  {
    operation: publicOperationName("list.addAccount"),
    graphqlType: "mutation",
    graphqlField: "addListAccount",
    graphqlArgs: ["input"],
    graphqlReturnType: "List",
    httpMethod: "post",
    httpPath: "/api/v1/lists/{id}/accounts",
    httpRequestRef: undefined,
    httpRequestRequiredFields: ["accountId"],
    httpResponseDataRef: "#/components/schemas/List",
  },
  {
    operation: publicOperationName("list.removeAccount"),
    graphqlType: "mutation",
    graphqlField: "removeListAccount",
    graphqlArgs: ["input"],
    graphqlReturnType: "List",
    httpMethod: "delete",
    httpPath: "/api/v1/lists/{id}/accounts",
    httpRequestRef: undefined,
    httpRequestRequiredFields: ["accountId"],
    httpResponseDataRef: "#/components/schemas/List",
  },
  {
    operation: publicOperationName("notification.dismiss"),
    graphqlType: "mutation",
    graphqlField: "dismissNotification",
    graphqlArgs: ["id"],
    graphqlReturnType: "DeletedEntity",
    httpMethod: "post",
    httpPath: "/api/v1/notifications/{id}/dismiss",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/DeletedEntity",
  },
  {
    operation: publicOperationName("notification.clear"),
    graphqlType: "mutation",
    graphqlField: "clearNotifications",
    graphqlArgs: ["adapter", "origin"],
    graphqlReturnType: "Boolean",
    httpMethod: "post",
    httpPath: "/api/v1/notifications/clear",
    httpRequestRef: undefined,
    httpResponseInlineFields: ["ok"],
    httpResponseDataRef: undefined,
  },
  {
    operation: publicOperationName("post.history"),
    graphqlType: "query",
    graphqlField: "postHistory",
    graphqlArgs: ["id"],
    graphqlReturnType: "PostRevision",
    graphqlReturnTypeSignature: "[PostRevision!]",
    httpMethod: "get",
    httpPath: "/api/v1/posts/{id}/history",
    httpRequestRef: undefined,
    httpResponseInlineFields: ["revisions"],
    httpResponseDataRef: undefined,
  },
  {
    operation: publicOperationName("filter.list"),
    graphqlType: "query",
    graphqlField: "filters",
    graphqlArgs: ["adapter", "origin", "page"],
    graphqlReturnType: "FilterConnection",
    httpMethod: "get",
    httpPath: "/api/v1/filters",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/Filter",
  },
  {
    operation: publicOperationName("filter.get"),
    graphqlType: "query",
    graphqlField: "filter",
    graphqlArgs: ["id"],
    graphqlReturnType: "Filter",
    httpMethod: "get",
    httpPath: "/api/v1/filters/{id}",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/Filter",
  },
  {
    operation: publicOperationName("filter.create"),
    graphqlType: "mutation",
    graphqlField: "createFilter",
    graphqlArgs: ["input"],
    graphqlReturnType: "Filter",
    httpMethod: "post",
    httpPath: "/api/v1/filters",
    httpRequestRef: undefined,
    httpRequestRequiredFields: ["context", "keywords", "origin", "title"],
    httpResponseDataRef: "#/components/schemas/Filter",
  },
  {
    operation: publicOperationName("filter.update"),
    graphqlType: "mutation",
    graphqlField: "updateFilter",
    graphqlArgs: ["input"],
    graphqlReturnType: "Filter",
    httpMethod: "patch",
    httpPath: "/api/v1/filters/{id}",
    httpRequestRef: undefined,
    httpRequestRequiredFields: ["context", "keywords", "title"],
    httpResponseDataRef: "#/components/schemas/Filter",
  },
  {
    operation: publicOperationName("filter.delete"),
    graphqlType: "mutation",
    graphqlField: "deleteFilter",
    graphqlArgs: ["id"],
    graphqlReturnType: "DeletedEntity",
    httpMethod: "delete",
    httpPath: "/api/v1/filters/{id}",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/DeletedEntity",
  },
  {
    operation: publicOperationName("scheduledPost.list"),
    graphqlType: "query",
    graphqlField: "scheduledPosts",
    graphqlArgs: ["adapter", "origin", "page"],
    graphqlReturnType: "ScheduledPostConnection",
    httpMethod: "get",
    httpPath: "/api/v1/scheduled-posts",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/ScheduledPost",
  },
  {
    operation: publicOperationName("scheduledPost.get"),
    graphqlType: "query",
    graphqlField: "scheduledPost",
    graphqlArgs: ["id"],
    graphqlReturnType: "ScheduledPost",
    httpMethod: "get",
    httpPath: "/api/v1/scheduled-posts/{id}",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/ScheduledPost",
  },
  {
    operation: publicOperationName("scheduledPost.create"),
    graphqlType: "mutation",
    graphqlField: "schedulePost",
    graphqlArgs: ["input"],
    graphqlReturnType: "ScheduledPost",
    httpMethod: "post",
    httpPath: "/api/v1/scheduled-posts",
    httpRequestRef: "#/components/schemas/SchedulePostRequest",
    httpResponseDataRef: "#/components/schemas/ScheduledPost",
  },
  {
    operation: publicOperationName("scheduledPost.update"),
    graphqlType: "mutation",
    graphqlField: "updateScheduledPost",
    graphqlArgs: ["input"],
    graphqlReturnType: "ScheduledPost",
    httpMethod: "patch",
    httpPath: "/api/v1/scheduled-posts/{id}",
    httpRequestRef: undefined,
    httpRequestRequiredFields: ["scheduledAt"],
    httpResponseDataRef: "#/components/schemas/ScheduledPost",
  },
  {
    operation: publicOperationName("scheduledPost.delete"),
    graphqlType: "mutation",
    graphqlField: "deleteScheduledPost",
    graphqlArgs: ["id"],
    graphqlReturnType: "DeletedEntity",
    httpMethod: "delete",
    httpPath: "/api/v1/scheduled-posts/{id}",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/DeletedEntity",
  },
  {
    operation: publicOperationName("instance.oauthMetadata"),
    graphqlType: "query",
    graphqlField: "oauthMetadata",
    graphqlArgs: ["adapter", "origin"],
    graphqlReturnType: "OAuthMetadata",
    httpMethod: "get",
    httpPath: "/api/v1/instances/{origin}/oauth",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/OAuthMetadata",
  },
  {
    operation: publicOperationName("instance.peers"),
    graphqlType: "query",
    graphqlField: "peers",
    graphqlArgs: ["adapter", "origin"],
    graphqlReturnType: "InstancePeers",
    httpMethod: "get",
    httpPath: "/api/v1/instances/{origin}/peers",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/InstancePeers",
  },
  {
    operation: publicOperationName("auth.registerClient"),
    graphqlType: "mutation",
    graphqlField: "registerOAuthClient",
    graphqlArgs: ["input"],
    graphqlReturnType: "OAuthClientRegistration",
    httpMethod: "post",
    httpPath: "/api/v1/auth/clients",
    httpRequestRef: "#/components/schemas/RegisterOAuthClientRequest",
    httpResponseDataRef: "#/components/schemas/OAuthClientRegistration",
  },
  {
    operation: publicOperationName("post.context"),
    graphqlType: "query",
    graphqlField: "postContext",
    graphqlArgs: ["id"],
    graphqlReturnType: "PostContext",
    httpMethod: "get",
    httpPath: "/api/v1/posts/{id}/context",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/PostContext",
  },
  {
    operation: publicOperationName("post.quotes"),
    graphqlType: "query",
    graphqlField: "postQuotes",
    graphqlArgs: ["id", "page"],
    graphqlReturnType: "PostConnection",
    httpMethod: "get",
    httpPath: "/api/v1/posts/{id}/quotes",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/Post",
  },
  {
    operation: publicOperationName("post.translate"),
    graphqlType: "mutation",
    graphqlField: "translatePost",
    graphqlArgs: ["input"],
    graphqlReturnType: "PostTranslation",
    httpMethod: "post",
    httpPath: "/api/v1/posts/{id}/translate",
    httpRequestRef: "#/components/schemas/TranslatePostRequest",
    httpResponseDataRef: "#/components/schemas/PostTranslation",
  },
  {
    operation: publicOperationName("media.get"),
    graphqlType: "query",
    graphqlField: "media",
    graphqlArgs: ["id"],
    graphqlReturnType: "MediaAttachment",
    httpMethod: "get",
    httpPath: "/api/v1/media/{id}",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/MediaAttachment",
  },
  {
    operation: publicOperationName("notification.groups"),
    graphqlType: "query",
    graphqlField: "notificationGroups",
    graphqlArgs: ["adapter", "origin", "page", "types"],
    graphqlReturnType: "NotificationGroupConnection",
    httpMethod: "get",
    httpPath: "/api/v1/notifications/groups",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/NotificationGroup",
  },
  {
    operation: publicOperationName("bookmarkFolder.list"),
    graphqlType: "query",
    graphqlField: "bookmarkFolders",
    graphqlArgs: ["adapter", "origin", "page"],
    graphqlReturnType: "BookmarkFolderConnection",
    httpMethod: "get",
    httpPath: "/api/v1/bookmark-folders",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/BookmarkFolder",
  },
  {
    operation: publicOperationName("bookmarkFolder.create"),
    graphqlType: "mutation",
    graphqlField: "createBookmarkFolder",
    graphqlArgs: ["input"],
    graphqlReturnType: "BookmarkFolder",
    httpMethod: "post",
    httpPath: "/api/v1/bookmark-folders",
    httpRequestRef: "#/components/schemas/CreateBookmarkFolderRequest",
    httpResponseDataRef: "#/components/schemas/BookmarkFolder",
  },
  {
    operation: publicOperationName("bookmarkFolder.update"),
    graphqlType: "mutation",
    graphqlField: "updateBookmarkFolder",
    graphqlArgs: ["input"],
    graphqlReturnType: "BookmarkFolder",
    httpMethod: "patch",
    httpPath: "/api/v1/bookmark-folders/{id}",
    httpRequestRef: "#/components/schemas/UpdateBookmarkFolderRequest",
    httpResponseDataRef: "#/components/schemas/BookmarkFolder",
  },
  {
    operation: publicOperationName("bookmarkFolder.delete"),
    graphqlType: "mutation",
    graphqlField: "deleteBookmarkFolder",
    graphqlArgs: ["id"],
    graphqlReturnType: "DeletedEntity",
    httpMethod: "delete",
    httpPath: "/api/v1/bookmark-folders/{id}",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/DeletedEntity",
  },
  {
    operation: publicOperationName("bookmarkFolder.addPost"),
    graphqlType: "mutation",
    graphqlField: "addPostToBookmarkFolder",
    graphqlArgs: ["input"],
    graphqlReturnType: "BookmarkFolder",
    httpMethod: "post",
    httpPath: "/api/v1/bookmark-folders/{id}/posts",
    httpRequestRef: "#/components/schemas/BookmarkFolderPostRequest",
    httpResponseDataRef: "#/components/schemas/BookmarkFolder",
  },
  {
    operation: publicOperationName("bookmarkFolder.removePost"),
    graphqlType: "mutation",
    graphqlField: "removePostFromBookmarkFolder",
    graphqlArgs: ["input"],
    graphqlReturnType: "BookmarkFolder",
    httpMethod: "delete",
    httpPath: "/api/v1/bookmark-folders/{id}/posts/{postId}",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/BookmarkFolder",
  },
  {
    operation: publicOperationName("timeline.local"),
    graphqlType: "query",
    graphqlField: "localTimeline",
    graphqlArgs: ["adapter", "origin", "page"],
    graphqlReturnType: "TimelineConnection",
    httpMethod: "get",
    httpPath: "/api/v1/timelines/local",
    httpRequestRef: undefined,
    httpResponseDataRef: "#/components/schemas/Post",
  },
] as const;

interface ReservedOperation {
  readonly operation: PublicOperationName;
  readonly graphqlType: "query" | "mutation";
  readonly graphqlField: string;
  readonly graphqlReturnType: string;
  readonly httpMethod: "get" | "post" | "patch" | "delete";
  readonly httpPath: string;
  readonly requiresAuth: boolean;
}

export const reservedOperationMatrix: readonly ReservedOperation[] = [];

export const implementedHttpOnlyOperations = new Set([
  "POST /api/v1/media",
  "GET /api/v1/streams",
  "GET /api/v1/streams/timelines/home",
  "GET /api/v1/streams/timelines/public",
  "GET /api/v1/streams/notifications",
]);

export const reservedHttpOnlyOperations = new Set<string>();

export const authenticatedHttpOnlyOperations = new Set([
  "POST /api/v1/media",
  "PATCH /api/v1/media/{id}",
  "DELETE /api/v1/media/{id}",
  "GET /api/v1/streams/timelines/home",
  "GET /api/v1/streams/notifications",
]);

export const standaloneHttpOperations = new Set([
  "GET /health",
  "GET /api/v1",
  "GET /api/v1/openapi.json",
]);

export const standaloneGraphQLOperations = new Set([
  "query apiVersion",
  "query health",
  "subscription notificationStream",
  "subscription timelineStream",
]);

export const reservedGraphQLOperations = new Set(
  reservedOperationMatrix.map((operation) => `${operation.graphqlType} ${operation.graphqlField}`),
);

function publicOperationName<Name extends PublicOperationName>(name: Name): Name {
  return name;
}
