import { capability, createCapabilitySet } from "@activityplug/core";

export function createMisskeyStaticCapabilities() {
  return createCapabilitySet({
    "auth.oauth.authorizationCode": capability("supported"),
    "auth.oauth.refreshToken": capability(
      "unsupported",
      "Misskey OAuth access tokens do not use refresh tokens.",
    ),
    "auth.oauth.clientCredentials": capability(
      "unsupported",
      "Client-credentials OAuth is not mapped by this adapter.",
    ),
    "auth.passkey": capability("unsupported", "Passkey auth is not mapped by this adapter."),
    "auth.tokenInjection": capability("supported"),
    "instance.nodeInfo": capability("supported"),
    "instance.peers": capability("unsupported", "Peer listing is not mapped by this adapter."),
    "accounts.relationships": capability("supported"),
    "accounts.lookupById": capability("supported"),
    "accounts.lookupByHandle": capability("supported"),
    "accounts.updateProfile": capability("supported"),
    "accounts.followers": capability("supported"),
    "accounts.following": capability("supported"),
    "posts.read": capability("supported"),
    "posts.create": capability("supported"),
    "posts.delete": capability("supported"),
    "posts.update": capability("unsupported", "Misskey does not expose stable note editing."),
    "posts.reply": capability("supported"),
    "posts.quote": capability("supported"),
    "posts.translate": capability("unsupported", "Post translation is not mapped by this adapter."),
    "posts.history": capability("unsupported", "Misskey does not expose note edit history."),
    "timelines.home": capability("supported"),
    "timelines.public": capability("supported"),
    "timelines.local": capability("supported"),
    "timelines.hashtag": capability("supported"),
    "media.upload": capability("supported"),
    "media.update": capability("supported"),
    "media.delete": capability("supported"),
    "media.remoteUrlUpload": capability("supported"),
    "media.urlIngestion": capability(
      "unsupported",
      "URL media ingestion is not mapped by this adapter.",
    ),
    "polls.create": capability("supported"),
    "polls.read": capability("supported"),
    "polls.vote": capability("supported"),
    "notifications.list": capability("supported"),
    "notifications.grouped": capability(
      "unsupported",
      "Misskey notifications are returned as a flat list by this adapter.",
    ),
    "notifications.pleromaEmojiReaction": capability(
      "unsupported",
      "Pleroma-specific notification types do not apply to Misskey.",
    ),
    "notifications.pleromaChatMention": capability(
      "unsupported",
      "Pleroma-specific notification types do not apply to Misskey.",
    ),
    "notifications.pleromaReport": capability(
      "unsupported",
      "Pleroma-specific notification types do not apply to Misskey.",
    ),
    "notifications.dismiss": capability(
      "unsupported",
      "Misskey does not expose a verified single-notification dismiss endpoint.",
    ),
    "notifications.clear": capability(
      "unsupported",
      "Misskey exposes mark-all-as-read, not a portable notification clear operation.",
    ),
    "notifications.unreadCount": capability(
      "unsupported",
      "Misskey does not expose a portable notification unread count endpoint.",
    ),
    "lists.read": capability("supported"),
    "lists.create": capability("supported"),
    "lists.update": capability("supported"),
    "lists.delete": capability("supported"),
    "lists.members": capability("supported"),
    "timelines.list": capability("supported"),
    "followRequests.list": capability("supported"),
    "followRequests.accept": capability("supported"),
    "followRequests.reject": capability("supported"),
    "filters.read": capability(
      "unsupported",
      "Misskey filter-like moderation settings are not mapped.",
    ),
    "filters.create": capability(
      "unsupported",
      "Misskey filter-like moderation settings are not mapped.",
    ),
    "filters.update": capability(
      "unsupported",
      "Misskey filter-like moderation settings are not mapped.",
    ),
    "filters.delete": capability(
      "unsupported",
      "Misskey filter-like moderation settings are not mapped.",
    ),
    "scheduledPosts.read": capability("unsupported", "Misskey does not expose scheduled notes."),
    "scheduledPosts.create": capability("unsupported", "Misskey does not expose scheduled notes."),
    "scheduledPosts.update": capability("unsupported", "Misskey does not expose scheduled notes."),
    "scheduledPosts.delete": capability("unsupported", "Misskey does not expose scheduled notes."),
    "search.accounts": capability("supported"),
    "search.posts": capability("supported"),
    "search.hashtags": capability("supported"),
    "social.follow": capability("supported"),
    "social.block": capability("supported"),
    "social.mute": capability("supported"),
    "social.favourite": capability("supported"),
    "social.bookmark": capability(
      "unsupported",
      "Misskey favorites are exposed through favourite operations; clip-based bookmarks are not mapped.",
    ),
    "social.bookmarkFolders": capability(
      "unsupported",
      "Bookmark folders are not mapped by this adapter.",
    ),
    "social.boost": capability("supported"),
    "social.reaction": capability("supported"),
    "streaming.timeline": capability("supported"),
    "streaming.notifications": capability("supported"),
    "streaming.conversations": capability(
      "unsupported",
      "Streaming is not implemented by this adapter yet.",
    ),
  });
}
