import { capability, createCapabilitySet } from "@activityplug/core";

export function createMisskeyStaticCapabilities() {
  return createCapabilitySet({
    "auth.oauth.authorizationCode": capability("supported"),
    "auth.oauth.refreshToken": capability(
      "unsupported",
      "Misskey OAuth access tokens do not use refresh tokens.",
    ),
    "auth.tokenInjection": capability("supported"),
    "instance.nodeInfo": capability("supported"),
    "accounts.relationships": capability("supported"),
    "accounts.lookupById": capability("supported"),
    "accounts.lookupByHandle": capability("supported"),
    "posts.read": capability("supported"),
    "posts.create": capability("supported"),
    "posts.delete": capability("supported"),
    "posts.update": capability("unsupported", "Misskey does not expose stable note editing."),
    "posts.reply": capability("supported"),
    "posts.quote": capability("supported"),
    "posts.history": capability("unsupported", "Misskey does not expose note edit history."),
    "timelines.home": capability("supported"),
    "timelines.public": capability("supported"),
    "timelines.local": capability("supported"),
    "timelines.hashtag": capability("supported"),
    "media.upload": capability("supported"),
    "polls.create": capability("supported"),
    "polls.read": capability("supported"),
    "polls.vote": capability("supported"),
    "notifications.list": capability("supported"),
    "notifications.grouped": capability(
      "unsupported",
      "Misskey notifications are returned as a flat list by this adapter.",
    ),
    "notifications.dismiss": capability(
      "unsupported",
      "Misskey does not expose a verified single-notification dismiss endpoint.",
    ),
    "notifications.clear": capability("supported"),
    "notifications.unreadCount": capability(
      "unsupported",
      "Misskey does not expose a portable notification unread count endpoint.",
    ),
    "lists.read": capability("supported"),
    "lists.create": capability("supported"),
    "lists.update": capability("supported"),
    "lists.delete": capability("supported"),
    "lists.members": capability("supported"),
    "timelines.list": capability("supported"),
    "followRequests.list": capability("supported"),
    "followRequests.accept": capability("supported"),
    "followRequests.reject": capability("supported"),
    "filters.read": capability(
      "unsupported",
      "Misskey filter-like moderation settings are not mapped.",
    ),
    "filters.create": capability(
      "unsupported",
      "Misskey filter-like moderation settings are not mapped.",
    ),
    "filters.update": capability(
      "unsupported",
      "Misskey filter-like moderation settings are not mapped.",
    ),
    "filters.delete": capability(
      "unsupported",
      "Misskey filter-like moderation settings are not mapped.",
    ),
    "scheduledPosts.read": capability("unsupported", "Misskey does not expose scheduled notes."),
    "scheduledPosts.create": capability("unsupported", "Misskey does not expose scheduled notes."),
    "scheduledPosts.update": capability("unsupported", "Misskey does not expose scheduled notes."),
    "scheduledPosts.delete": capability("unsupported", "Misskey does not expose scheduled notes."),
    "search.accounts": capability("supported"),
    "search.posts": capability("supported"),
    "search.hashtags": capability("supported"),
    "social.follow": capability("supported"),
    "social.block": capability("supported"),
    "social.mute": capability("supported"),
    "social.favourite": capability("supported"),
    "social.bookmark": capability(
      "unsupported",
      "Misskey bookmark and clip semantics are not mapped by this adapter yet.",
    ),
    "social.boost": capability("supported"),
    "social.reaction": capability("supported"),
  });
}
